UPDATE `creature` SET `spawndist` =10 WHERE `guid` =10233525;
UPDATE `creature` SET `equipment_id` =0 WHERE `id` =32871;
DELETE FROM `creature_loot_template` WHERE `entry` = 32914;
DELETE FROM `creature_loot_template` WHERE `entry` = 33354;
DELETE FROM `creature_loot_template` WHERE `entry` = 33355;
DELETE FROM `creature_loot_template` WHERE `entry` = 33430;
DELETE FROM `creature_loot_template` WHERE `entry` = 33431;
DELETE FROM `creature_loot_template` WHERE `entry` = 33525;
DELETE FROM `creature_loot_template` WHERE `entry` = 33526;
DELETE FROM `creature_loot_template` WHERE `entry` = 33527;
DELETE FROM `creature_loot_template` WHERE `entry` = 33699;
DELETE FROM `creature_loot_template` WHERE `entry` = 33722;
DELETE FROM `creature_loot_template` WHERE `entry` = 33723;
DELETE FROM `creature_loot_template` WHERE `entry` = 33731;
DELETE FROM `creature_loot_template` WHERE `entry` = 33732;
DELETE FROM `creature_loot_template` WHERE `entry` = 33734;
DELETE FROM `creature_loot_template` WHERE `entry` = 33735;
DELETE FROM `creature_loot_template` WHERE `entry` = 33737;
DELETE FROM `creature_loot_template` WHERE `entry` = 33741;
DELETE FROM `creature_loot_template` WHERE `entry` = 33773;
DELETE FROM `creature_loot_template` WHERE `entry` = 33818;
DELETE FROM `creature_loot_template` WHERE `entry` = 33819;
DELETE FROM `creature_loot_template` WHERE `entry` = 33820;
DELETE FROM `creature_loot_template` WHERE `entry` = 33822;
DELETE FROM `creature_loot_template` WHERE `entry` = 33823;
DELETE FROM `creature_loot_template` WHERE `entry` = 33824;
DELETE FROM `creature_loot_template` WHERE `entry` = 33827;
DELETE FROM `creature_loot_template` WHERE `entry` = 33828;
DELETE FROM `creature_loot_template` WHERE `entry` = 33829;
DELETE FROM `creature_loot_template` WHERE `entry` = 33830;
DELETE FROM `creature_loot_template` WHERE `entry` = 33831;
DELETE FROM `creature_loot_template` WHERE `entry` = 33832;
DELETE FROM `creature_loot_template` WHERE `entry` = 34069;
DELETE FROM `creature_loot_template` WHERE `entry` = 34085;
DELETE FROM `creature_loot_template` WHERE `entry` = 34086;
DELETE FROM `creature_loot_template` WHERE `entry` = 34133;
DELETE FROM `creature_loot_template` WHERE `entry` = 34134;
DELETE FROM `creature_loot_template` WHERE `entry` = 34135;
DELETE FROM `creature_loot_template` WHERE `entry` = 34137;
DELETE FROM `creature_loot_template` WHERE `entry` = 34139;
DELETE FROM `creature_loot_template` WHERE `entry` = 34141;
DELETE FROM `creature_loot_template` WHERE `entry` = 34142;
DELETE FROM `creature_loot_template` WHERE `entry` = 34185;
DELETE FROM `creature_loot_template` WHERE `entry` = 34186;
DELETE FROM `creature_loot_template` WHERE `entry` = 34190;
DELETE FROM `creature_loot_template` WHERE `entry` = 34191;
DELETE FROM `creature_loot_template` WHERE `entry` = 34193;
DELETE FROM `creature_loot_template` WHERE `entry` = 34196;
DELETE FROM `creature_loot_template` WHERE `entry` = 34197;
DELETE FROM `creature_loot_template` WHERE `entry` = 34198;
DELETE FROM `creature_loot_template` WHERE `entry` = 34199;
DELETE FROM `creature_loot_template` WHERE `entry` = 34201;
DELETE FROM `creature_loot_template` WHERE `entry` = 34214;
DELETE FROM `creature_loot_template` WHERE `entry` = 34217;
DELETE FROM `creature_loot_template` WHERE `entry` = 34220;
DELETE FROM `creature_loot_template` WHERE `entry` = 34226;
DELETE FROM `creature_loot_template` WHERE `entry` = 34229;
DELETE FROM `creature_loot_template` WHERE `entry` = 34236;
DELETE FROM `creature_loot_template` WHERE `entry` = 34237;
DELETE FROM `creature_loot_template` WHERE `entry` = 34245;
DELETE FROM `creature_loot_template` WHERE `entry` = 34267;
DELETE FROM `creature_loot_template` WHERE `entry` = 34268;
DELETE FROM `creature_loot_template` WHERE `entry` = 34269;
DELETE FROM `creature_loot_template` WHERE `entry` = 34270;
DELETE FROM `creature_loot_template` WHERE `entry` = 34271;
DELETE FROM `creature_loot_template` WHERE `entry` = 34272;
DELETE FROM `creature_loot_template` WHERE `entry` = 34273;
DELETE FROM `creature_loot_template` WHERE `entry` = 34274;
DELETE FROM `gameobject_loot_template` WHERE `mincountOrRef` = -12022;
DELETE FROM `gameobject_loot_template` WHERE `mincountOrRef` = -12021;
DELETE FROM `gameobject_loot_template` WHERE `mincountOrRef` = -12020;
DELETE FROM `gameobject_loot_template` WHERE `mincountOrRef` = -34129;
DELETE FROM `gameobject_loot_template` WHERE `mincountOrRef` = -34130;
DELETE FROM `gameobject_loot_template` WHERE `entry` = 26956;
DELETE FROM `reference_loot_template` WHERE `entry` = 34113;
DELETE FROM `reference_loot_template` WHERE `entry` = 34114;
DELETE FROM `reference_loot_template` WHERE `entry` = 34115;
DELETE FROM `reference_loot_template` WHERE `entry` = 34155;
DELETE FROM `reference_loot_template` WHERE `entry` = 34156;

-- 去掉英雄模式脚本 等更新或自己写 英雄模式默认沿用普通模式
UPDATE `creature_template` SET AIName='' WHERE `entry` = 34142;
UPDATE `creature_template` SET AIName='' WHERE `entry` = 34236;

UPDATE `creature` SET `MovementType`='0' WHERE (`guid`='10233522');
UPDATE `gameobject_template` SET `data1`='0' WHERE (`entry`='201875');
UPDATE `gameobject_template` SET `data1`='0' WHERE (`entry`='202179');
UPDATE `gameobject_template` SET `data1`='0' WHERE (`entry`='202180');
UPDATE `gameobject_template` SET `data1`='0' WHERE (`entry`='201874');
UPDATE `gameobject_template` SET `data1`='0' WHERE (`entry`='201872');
UPDATE `gameobject_template` SET `data1`='0' WHERE (`entry`='202177');
UPDATE `gameobject_template` SET `data1`='0' WHERE (`entry`='202178');
UPDATE `gameobject_template` SET `data1`='0' WHERE (`entry`='201873');
UPDATE `creature_loot_template` SET `mincountOrRef`='0' WHERE (`entry`='35350') AND (`item`='2');
DELETE FROM `reference_loot_template` WHERE `entry` = 35091;
DELETE FROM `reference_loot_template` WHERE `entry` = 35092;
DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId`='17') AND (`SourceGroup`='0') AND (`SourceEntry`='66588') AND (`SourceId`='0') AND (`ElseGroup`='1') AND (`ConditionTypeOrReference`='31') AND (`ConditionTarget`='1') AND (`ConditionValue1`='3') AND (`ConditionValue2`='35092') AND (`ConditionValue3`='0');
DELETE FROM `creature_loot_template` WHERE (`entry`='35350') AND (`item`='2');